### ISSUE TITLE
GLFWError: (65537) b'The GLFW library is not initialized'

### ISSUE THREAD

**Issue by HJX-exoskeleton** [NoneJou072/robopal#12]
python demo_visual_servo.py 

INFO:root:Activated agents: ['arm0']
Traceback (most recent call last):
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/demos/demo_visual_servo.py", line 125, in <module>
    env.step()
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/demos/demo_visual_servo.py", line 70, in step
    cam2aruco_r, cam2aruco_p, detected_already = self.aruco_detection(marker_size)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/demos/demo_visual_servo.py", line 42, in aruco_detection
    rvec, tvec, _ = cv2.aruco.estimatePoseSingleMarkers(
AttributeError: module 'cv2.aruco' has no attribute 'estimatePoseSingleMarkers'
/home/hjx/anaconda3/envs/hjx/lib/python3.9/site-packages/glfw/__init__.py:914: GLFWError: (65537) b'The GLFW library is not initialized'

**Comment by NoneJou072** [comment]
Upgrade to the latest opencv and opencv-contrib version

**Comment by HJX-exoskeleton** [comment]
Thanks!
The problem was resolved using the pip installation:
pip install opencv-python
pip install opencv-contrib-python
