### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)

### ISSUE THREAD

**Issue by HJX-exoskeleton** [NoneJou072/robopal#14]
python demo_tele_calibrate.py 
INFO:root:Activated agents: ['arm0']
Press arrow keys to move the end effector along the x/y-axis.
Press ctrl + arrow keys to move the end effector along the z-axis.
Press shift + arrow keys to rotate the end effector along the x/y-axis.
Press ctrl + shift + arrow keys to rotate the end effector along the z-axis.
Press esc to exit.
Traceback (most recent call last):
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/demos/demo_tele_calibrate.py", line 34, in <module>
    env.step(action)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/envs/robot.py", line 66, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/envs/robot.py", line 77, in step
    joint_inputs = self.controller.step_controller(action)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/controllers/task_ik_controller.py", line 64, in step_controller
    ret[agent] = self.ik(p_goal, r_goal, agent)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/controllers/task_ik_controller.py", line 77, in ik
    x, _ = minimize.least_squares(x, ik_target, self.robot.mani_joint_bounds[agent], jacobian=jac_target, eps=1e-6, verbose=0)
  File "/home/hjx/anaconda3/envs/hjx/lib/python3.9/site-packages/mujoco/minimize.py", line 247, in least_squares
    r = residual(x)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/controllers/task_ik_controller.py", line 75, in <lambda>
    ik_target = lambda x: self._ik_res(x, pos=pos, quat=quat, reg_target=x_prev, radius=radius, reg=.01, agent=agent)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/controllers/task_ik_controller.py", line 107, in _ik_res
    return np.hstack((res_pos, res_quat, res_reg))
  File "/home/hjx/anaconda3/envs/hjx/lib/python3.9/site-packages/numpy/core/shape_base.py", line 357, in hstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)
/home/hjx/anaconda3/envs/hjx/lib/python3.9/site-packages/glfw/__init__.py:914: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)

**Comment by DevilCJS89** [comment]
感觉像是python pkg的版本问题

**Comment by NoneJou072** [comment]
似乎是mujoco 版本的问题，尝试降低一个小版本到3.1.4

**Comment by DevilCJS89** [comment]
当我在运行这个demo时：python demo_motion_planning.py 
我遇到了下面这个问题：

Traceback (most recent call last):
  File "/home/cjs/MUJOCO/robopal/robopal/demos/demo_motion_planning.py", line 20, in <module>
    path = rrt_star(current_pos, goal_pos, env)
  File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 433, in rrt_star
    path = rrt.planning(animation=show_animation)
  File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 101, in planning
    if self.is_inside_play_area(new_node, self.play_area) and not self.is_collide(self.sim, new_node):
  File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 395, in is_collide
    qpos = sim.ik(target_pos, target_rot, sim.robot.get_arm_qpos())
AttributeError: 'RobotEnv' object has no attribute 'ik'

我看了

**Comment by DevilCJS89** [comment]
大佬，个人打算基于这个框架开发自己的需求，方不方便加个联系方式
WX：JSDevil89

**Comment by DevilCJS89** [comment]
强化学习部分跟gymnasium-robotics的demo很像
B站中的视频也很棒！
致敬大佬
