### ISSUE TITLE
python demo_motion_planning.py

### ISSUE THREAD

**Issue by DevilCJS89** [NoneJou072/robopal#15]
当我在运行这个demo时：python demo_motion_planning.py
我遇到了下面这个问题：
看起来像是python版本的问题：AttributeError: 'RobotEnv' object has no attribute 'ik'
Traceback (most recent call last):
File "/home/cjs/MUJOCO/robopal/robopal/demos/demo_motion_planning.py", line 20, in
path = rrt_star(current_pos, goal_pos, env)
File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 433, in rrt_star
path = rrt.planning(animation=show_animation)
File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 101, in planning
if self.is_inside_play_area(new_node, self.play_area) and not self.is_collide(self.sim, new_node):
File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 395, in is_collide
qpos = sim.ik(target_pos, target_rot, sim.robot.get_arm_qpos())
AttributeError: 'RobotEnv' object has no attribute 'ik'

**Comment by DevilCJS89** [comment]
大佬，个人打算基于这个框架开发自己的需求，方不方便加个联系方式
WX：JSDevil89

**Comment by NoneJou072** [comment]
不好意思 ，由于框架迭代速度飞快，demo_motion_planning  年久失修，有一些问题，已经加你 vx 了

**Comment by NoneJou072** [comment]
> 不好意思 ，由于框架迭代速度飞快，demo_motion_planning 年久失修，有一些问题，已经加你 vx 了

已修复 demo_motion_planning 示例，可以正常规划
