### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by silencht** [NoneJou072/robopal#17]
Hi, 我在安装时出现了以下错误，您能为我提供一些指点吗？
我不是很熟悉mujoco这个库，我只是通过pip install来安装。这和目前网络博客中安装210等版本的操作不一样（他们需要把mujoco放到home下一个.mujoco目录下，然后修改basrc脚本并安装mujoco-py库）。所以我不知道是不是因为mujoco导致了该错误。
我的环境
```bash
(robopal) silencht@silencht-laptop:~/robopal$ conda list
# packages in environment at /home/silencht/miniconda3/envs/robopal:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
ca-certificates           2024.3.11            h06a4308_0  
etils                     1.3.0                    pypi_0    pypi
glfw                      2.7.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
mujoco                    3.1.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.4                   pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openssl                   3.0.13               h7f8727e_1  
pip                       24.0             py38h06a4308_0  
pyopengl                  3.1.7                    pypi_0    pypi
python                    3.8.19               h955ad1f_0  
readline                  8.2                  h5eee18b_0  
setuptools                69.5.1           py38h06a4308_0  
sqlite                    3.45.3               h5eee18b_0  
tk                        8.6.14               h39e8969_0  
typing-extensions         4.11.0                   pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0  
xz                        5.4.6                h5eee18b_1  
zipp                      3.18.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
(robopal) silencht@silencht-laptop:~/robopal$ 
```
这是我的错误信息(mujoco 3.1.5和3.1.4错误相同)
```bash
(robopal) silencht@silencht-laptop:~/robopal$ python -m robopal.demos.demo_controller
Available manipulators:
 1. DianaMed
 2. Panda
 3. UR5e
 4. DualDianaMed
Choose the manipulator:2
Available controllers:
 1.JNTIMP
 2.JNTVEL
 3.CARTIMP
 4.CARTIK
Choose the controller:1
INFO:root:Activated agents: ['arm0']
Traceback (most recent call last):
  File "/home/silencht/miniconda3/envs/robopal/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/silencht/miniconda3/envs/robopal/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/silencht/robopal/robopal/demos/demo_controller.py", line 42, in <module>
    env = RobotEnv(
  File "/home/silencht/robopal/robopal/envs/robot.py", line 32, in __init__
    super().__init__(
  File "/home/silencht/robopal/robopal/envs/base.py", line 42, in __init__
    self.robot: BaseRobot = robot()
  File "/home/silencht/robopal/robopal/robots/panda.py", line 16, in __init__
    super().__init__(
  File "/home/silencht/robopal/robopal/robots/base.py", line 77, in __init__
    agent: END_MAP[gripper](self.robot_data) for agent, gripper in zip(self.agents, gripper)
TypeError: 'NoneType' object is not iterable
```

**Comment by silencht** [comment]
当我切换到旧commit，好像成功运行了。

```bash
(robopal) silencht@silencht-laptop:~/robopal$ git checkout c8f668c
Note: checking out 'c8f668c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c8f668c add ur5e and bimanual robotic to the demo
(robopal) silencht@silencht-laptop:~/robopal$ git status
HEAD detached at c8f668c
nothing to commit, working tree clean
(robopal) silencht@silencht-laptop:~/robopal$ python -m robopal.demos.demo_controller
Available manipulators:
 1. DianaMed
 2. Panda
 3. UR5e
 4. DualDianaMed
Choose the manipulator:1
Available controllers:
 1.JNTIMP
 2.JNTVEL
 3.CARTIMP
 4.CARTIK
Choose the controller:1
INFO:root:Activated agents: ['arm0']
INFO:root:Environment has closed!

```

**Comment by NoneJou072** [comment]
抱歉，最新的一版 commit 有 bug，现在已经修复，感谢您的留言
