### ISSUE TITLE
运行demo失败

### ISSUE THREAD

**Issue by JustANoob903** [NoneJou072/robopal#20]
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/fff/robopal/robopal/__init__.py", line 2, in <module>
    from robopal.envs.base import make
  File "/home/fff/robopal/robopal/envs/__init__.py", line 6, in <module>
    from .manipulation_tasks.demo_pick_place import PickAndPlaceEnv
  File "/home/fff/robopal/robopal/envs/manipulation_tasks/demo_pick_place.py", line 6, in <module>
    from robopal.wrappers import GoalEnvWrapper
  File "/home/fff/robopal/robopal/wrappers/__init__.py", line 2, in <module>
    from .petting_zoo_wrapper import PettingStyleWrapper
  File "/home/fff/robopal/robopal/wrappers/petting_zoo_wrapper.py", line 13, in <module>
    class PettingStyleWrapper(ParallelEnv):
                              ^^^^^^^^^^^
NameError: name 'ParallelEnv' is not defined

**Comment by NoneJou072** [comment]
原因是缺少 pettingzoo 库，请 pip install pettingzoo，感谢您的 issue，我在最近的更新中加入了依赖检测提示。
