### ISSUE TITLE
robopal/robopal/demos/demo_tele_calibrate.py文件报错

### ISSUE THREAD

**Issue by HJX-exoskeleton** [NoneJou072/robopal#21]
大佬您好，我在运行robopal/robopal/demos/demo_tele_calibrate.py文件时，遇到了如下报错：
[13:56:32] INFO     mjcf model has been saved to               xml_splice.py:377
                    /home/hjx/hjx_file/mujoco_file/robopal/rob                  
                    opal/assets/robot.xml                                       
           INFO     Activated agents: ['arm0']                        base.py:80
Traceback (most recent call last):
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/demos/demo_tele_calibrate.py", line 15, in <module>
    env = RobotEnv(
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/envs/robot.py", line 34, in __init__
    super().__init__(
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/envs/base.py", line 64, in __init__
    self.robot = robot()
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/robots/diana_med.py", line 18, in __init__
    super().__init__(
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/robots/base.py", line 82, in __init__
    self.build_from_xml(xml_path)
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/robots/base.py", line 118, in build_from_xml
    self.robot_model = mujoco.MjModel.from_xml_path(filename=xml_path, assets=None)
ValueError: XML Error: Schema violation: unrecognized element

Element 'asset', line 0

环境的搭建应该没有问题，我在demos文件夹中哦运行别的python文件都可以成功，唯独demo_tele_calibrate.py这个有报错，不知道如何解决

**Comment by NoneJou072** [comment]
之前该demo存在bug，感谢您的提问，目前已经修复
