### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by kavinwkp** [NoneJou072/robopal#25]
```py
$ python demo_controllers.py                                             
Traceback (most recent call last):
  File "demo_controllers.py", line 4, in <module>
    from robopal.robots.diana_med import DianaMed
  File "/home/kavin/Documents/GitProjects/Mujoco/robopal/robopal/__init__.py", line 13, in <module>
    from robopal.envs.base import make
  File "/home/kavin/Documents/GitProjects/Mujoco/robopal/robopal/envs/__init__.py", line 6, in <module>
    from .manipulation_tasks.demo_pick_place import PickAndPlaceEnv
  File "/home/kavin/Documents/GitProjects/Mujoco/robopal/robopal/envs/manipulation_tasks/demo_pick_place.py", line 6, in <module>
    from robopal.wrappers import GoalEnvWrapper
  File "/home/kavin/Documents/GitProjects/Mujoco/robopal/robopal/wrappers/__init__.py", line 2, in <module>
    from .petting_zoo_wrapper import PettingStyleWrapper
  File "/home/kavin/Documents/GitProjects/Mujoco/robopal/robopal/wrappers/petting_zoo_wrapper.py", line 15, in <module>
    class PettingStyleWrapper(ParallelEnv):
  File "/home/kavin/Documents/GitProjects/Mujoco/robopal/robopal/wrappers/petting_zoo_wrapper.py", line 48, in PettingStyleWrapper
    def step(self, actions: dict[str, np.ndarray]):
TypeError: 'type' object is not subscriptable
```
And there is no numpy version 1.26.4.

**Comment by NoneJou072** [comment]
thanks, @kavinwkp . 
This is a feature of py3.9 and is not compatible with py3.8., we have fixed it in next commit.
Numpy version only needs to be >=1.23.5.
