### ISSUE TITLE
关于demo的一些问题

### ISSUE THREAD

**Issue by QWelkin** [NoneJou072/robopal#27]
**在运行demo_motion_planning时提示以下错误：**
Traceback (most recent call last):
  File "/home/qwk/anaconda3/envs/robopal/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/qwk/anaconda3/envs/robopal/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/qwk/robopal/robopal/demos/demo_motion_planning.py", line 21, in <module>
    path = rrt_star(current_pos, goal_pos, env)
  File "/home/qwk/robopal/robopal/controllers/planners/rrt.py", line 434, in rrt_star
    path = rrt.planning(animation=show_animation)
  File "/home/qwk/robopal/robopal/controllers/planners/rrt.py", line 119, in planning
    self.draw_graph(rnd_node)
  File "/home/qwk/robopal/robopal/controllers/planners/rrt.py", line 175, in draw_graph
    plt.clf()
NameError: name 'plt' is not defined

**在运行demo_devices时提示以下错误：**
Traceback (most recent call last):
  File "/home/qwk/anaconda3/envs/robopal/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/qwk/anaconda3/envs/robopal/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/qwk/robopal/robopal/demos/demo_devices.py", line 33, in <module>
    device.start()
  File "/home/qwk/robopal/robopal/devices/keyboard.py", line 32, in start
    listener = keyboard.Listener(
NameError: name 'keyboard' is not defined

另外在运行demo_visual_servo的时候能够正常运行，但是不清楚是什么原因使用键盘Ctrl+方向键无法控制机器人末端移动。
其他demo均可顺利运行！

**Comment by NoneJou072** [comment]
@QWelkin ，您好。
您的问题看起来是依赖安装不全导致的。
demo_motion_planning 需要使用 matplotlib 库，
demo_devices 需要使用 pynput 库，
您在运行时，终端里应该会有依赖缺失的 warning 显示 ，请通过 pip install *** 进行安装

**Comment by QWelkin** [comment]
1.重新安装matplotlib=3.9.1后能够运行demo_motion_planning了，感谢！
2.确实有warning提示安装pynput，但我已经安装有pynput=1.7.7，demo_devices仍然没能成功运行。

**Comment by NoneJou072** [comment]
> 1.重新安装matplotlib=3.9.1后能够运行demo_motion_planning了，感谢！ 2.确实有warning提示安装pynput，但我已经安装有pynput=1.7.7，demo_devices仍然没能成功运行。

demo_devices 存在其它的bug，已经在最新的 commit 中修复了。
如果您确实有warning提示安装pynput，并且您确认已经安装 pynput，您可以尝试 from pynput import keyboard 看看是否成功

**Comment by QWelkin** [comment]
**按照commit修改了，但还是无法正常运行，依旧出现报错：**
NameError: name 'keyboard' is not defined

**另外，虽然已经将opencv-python和opencv-contrib-python更新到最新版本，但还出现报错：**
GLFWError: (65537) b'The GLFW library is not initialized'

**Comment by NoneJou072** [comment]
> **按照commit修改了，但还是无法正常运行，依旧出现报错：** NameError: name 'keyboard' is not defined
> 
> **另外，虽然已经将opencv-python和opencv-contrib-python更新到最新版本，但还出现报错：** GLFWError: (65537) b'The GLFW library is not initialized'

是否在 python 命令行中尝试过 `from pynput import keyboard ` 呢

**Comment by QWelkin** [comment]
> > **按照commit修改了，但还是无法正常运行，依旧出现报错：** NameError: name 'keyboard' is not defined
> > **另外，虽然已经将opencv-python和opencv-contrib-python更新到最新版本，但还出现报错：** GLFWError: (65537) b'The GLFW library is not initialized'
> 
> 是否在 python 命令行中尝试过 `from pynput import keyboard ` 呢

你的意思是在demo_devices.py脚本中加`from pynput import keyboard ` 吗？

**Comment by NoneJou072** [comment]
@QWelkin 您在上面提到了`确实有warning提示安装pynput`, 所以我想您可以检查下 pynput 的安装是否存在问题，比如在新建一个 python 脚本，输入 from pynput import keyboard，再运行，看看有没有报错

**Comment by QWelkin** [comment]
pynput库安装应该是没有问题的。刚刚在工作站主机上面尝试，能够直接运行！估计是远程软件MobaXterm与pynput之间有一些不适配。

**Comment by QWelkin** [comment]
您是否有方法通过SSH完成demo的键盘交互控制，即在SSH运行demo_devices并且使用键盘对机械臂进行控制。

**Comment by NoneJou072** [comment]
> 您是否有方法通过SSH完成demo的键盘交互控制，即在SSH运行demo_devices并且使用键盘对机械臂进行控制。

这个我不太清楚哈
